### ISSUE TITLE
Change the views for login and sign up 

### ISSUE THREAD

**Issue by martinctl** [roxannecvl/whokipedia#21]
Change the views for login and signup to match the [Figma](https://www.figma.com/file/rx72AgNPISUhQ2si9RGFig/Whokipedia?type=design&node-id=0%3A1&mode=design&t=PTnIPHI7uR4vD2J7-1), which is displayed below. 

![image](https://github.com/roxannecvl/whokipedia/assets/91327170/55fdb9ce-86fe-4cc3-8cc5-384c84c93686)

**Comment by MaelArrive** [comment]
Done in issue #75
