### ISSUE TITLE
Add error feedback for guesses not in the list

### ISSUE THREAD

**Issue by JEANPRBT** [roxannecvl/whokipedia#96]
Here is one of the peer-review remarks. Fix that, maybe using the same error procedure as for already entered guesses.
> Besides that, there is one thing that is a usability mistake that I think will impact your
grade: if I try to type a guess that is not in the list, the interface doesn't give me any
error feedback. As a user, I need something to make me aware that I can't do that. One
solution is to add a "submit" button next to the input box, and disable it if the guess is
not in the list.

**Comment by roxannecvl** [comment]
This issue for me is not an actual issue, since when you try to type in a random name not in the list the name doesn't disappear / nothing happens so you see that it is not like the other times.
